

# Encoder
ENCODER_ENABLE = yes

# Send String
ENABLE_SEND_STRING = yes

# RGB Matrix
RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812
# SPLIT_KEYBOARD = yes

CONVERT_TO=liatris
RP2040_BOOTLOADER_DOUBLE_TAP_RESET = yes
CONSOLE_ENABLE = yes
