DEFAULT_FOLDER = splitkb/aurora/sofle_v2/rev1
CONVERT_TO=liatris
RP2040_BOOTLOADER_DOUBLE_TAP_RESET = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = yes
VIALRGB_ENABLE = yes
UNICODE_ENABLE = yes
KEY_LOCK_ENABLE = yes
# Later
# UNICODEMAP_ENABLE = yes
